dist: trusty

language: c

compiler: gcc

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libpcsclite-dev libgssglue-dev nettle-dev libtasn1-dev libgnutls-dev

script: ./bootstrap && ./configure && make
