dist: trusty
language: c
compiler: gcc
sudo: required

# safelist
branches:
  only:
  - integration

env:
  global:

addons:
  coverity_scan:
    project:
      name: "uglym8/rdesktop"
      description: "Unix client for Microsoft Remote Desktop Services. http://www.rdesktop.org"
    notification_email: uglym8@gmail.com
    build_command_prepend: "./bootstrap && ./configure"
    build_command:   "make"
    branch_pattern: integration

    #addons:
    #  sonarcloud:
    #    organization: uglym8-github
    #    branches:
    #        - integration


before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libpcsclite-dev libxcursor-dev libao-dev libasound2-dev libgssglue-dev

before_script:
- "./bootstrap"

script:
- "./configure"
  #- build-wrapper-linux-x86-64 --out-dir build-wrapper-out make clean all
  #- sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
