dist: trusty

language: c

compiler: gcc

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libpcsclite-dev
 - sudo apt-get install -y libtasn1-dev

script: ./bootstrap && ./configure && make
